### ISSUE TITLE
Фиксы по сервису

### ISSUE THREAD

**Issue by Krethub** [botxme/voenmeh#8]
- [x] Пофиксить шрифты на iOS

- [x] Пофиксить белый экран в настройках

- [x] Пофиксить лайт-строку поиска в ленте новостей с веб-версии

- [x] Фикс Сепаратора в расписании

- [x] Смена пэдинга на сепараторе и ячейке

- [x] Фикс шрифтов (st)

**Comment by VBIralo** [comment]
Не удается отловить баг с белым экраном настроек. Так что пока считаю, что фикс 😅 
Если отловите, дайте знать.
